[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "reachy_sim"
version = "0.1.0"
description = "RL environments for Reachy 2 in MuJoCo"
requires-python = "==3.10.*"

[tool.setuptools.packages.find]
include = ["reachy_sim*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
